run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gosec
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
